services:
  megasync:
    image: debian:stable-slim
    container_name: megasync
    volumes:
      # https://mega.nz/linux/repo/Debian_13/amd64/megacmd_2.2.0-2.1_amd64.deb
      - ./megacmd_2.2.0-2.1_amd64.deb:/tmp/megacmd.deb:ro
      - ./scripts:/scripts:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./mega.creds:/run/mega.creds:ro
      - ./megaCmd:/root/.megaCmd
      - ./data:/data

    entrypoint: >
      bash -c "
        bash /scripts/mega-init.bash &&
        bash /scripts/mega-login.bash &&
        bash /scripts/mega-customscript.bash &&
        tail -f /dev/null
      "
    tty: true
    init: true
